using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Data;

using MoreSlugcats;

using UnityEngine;

using IVec2 = RWCustom.IntVector2;

namespace JumpSlug.Pathfinding;

/// <summary>
/// Represents the path generated by the pathfinder in a format that is easier for the AI to consume
/// and allows it to be easily iterated over.
/// </summary>
public class Path {
    // these aren't private because it's more straightforward for the visualizer to use manual indexing
    // and the accessors can't be made const correct
    public int Cursor;
    public readonly List<IVec2> Nodes;
    public readonly List<ConnectionType> Connections;

    public int NodeCount => Nodes.Count;
    public int ConnectionCount => Connections.Count;

    /// <summary>
    /// Creates new path from the raw path generated by the pathfinder.
    /// </summary>
    /// <param name="endNode">the node at the destination of the path.</param>
    /// <param name="sharedGraph">the room specific graph the path was generated for.</param>
    public Path(PathNode endNode) {
        Nodes = new();
        Connections = new();
        var currentNode = endNode;
        while (currentNode is not null) {
            Nodes.Add(currentNode.GridPos);
            if (currentNode.Connection is not null) {
                Connections.Add(currentNode.Connection.Value.Type);
            }
            currentNode = currentNode.Connection?.Next;
        }
        Cursor = Nodes.Count - 1;
    }

    /// <summary>
    /// Access node at the current cursor position.
    /// </summary>
    /// <returns>
    /// Null if the cursor has moved past the end of the path.
    /// </returns>
    public IVec2? CurrentNode() {
        if (Cursor < 0) {
            return null;
        }
        return Nodes[Cursor];
    }
    /// <summary>
    /// Inspect previous or upcoming nodes without moving the cursor.
    /// </summary>
    /// <param name="offset">
    /// Offset from the cursor position, positive values look ahead, negative value look back.
    /// </param>
    /// <returns>
    /// Null if the specified offset falls outside the path.
    /// </returns>
    public IVec2? PeekNode(int offset) {
        if (Cursor - offset < 0) {
            return null;
        }
        return Nodes[Cursor - offset];
    }
    /// <summary>
    /// Access outgoing connection from the current cursor position.
    /// </summary>
    /// <returns>
    /// Null if the cursor has moved past the end of the path.
    /// </returns>
    public ConnectionType? CurrentConnection() {
        if (Cursor < 1) {
            return null;
        }
        return Connections[Cursor - 1];
    }
    /// <summary>
    /// Inspect outgoing connection from previous or upcoming nodes without moving the cursor.
    /// </summary>
    /// <param name="offset">
    /// Offset from the cursor position, positive values look ahead, negative value look back.
    /// </param>
    /// <returns>
    /// Null if the specified offset falls outside the path.
    /// </returns>
    public ConnectionType? PeekConnection(int offset) {
        if (Cursor - offset < 1) {
            return null;
        }
        return Connections[Cursor - offset - 1];
    }
    /// <summary>
    /// Move the cursor forward by one step.
    /// </summary>
    public void Advance() {
        Cursor -= 1;
    }
}

/// <summary>
/// Node used by the pathfinding algorithm when generating paths.
/// </summary>
public class PathNode {
    public IVec2 GridPos { get; }
    public PathConnection? Connection;
    public float PathCost;

    public float Heuristic { get; private set; }
    public float FCost => PathCost + Heuristic;

    /// <summary>
    /// Create new node at specified grid position.
    /// </summary>
    public PathNode(int x, int y) {
        GridPos = new IVec2(x, y);
        PathCost = 0;
        Heuristic = 0;
    }

    /// <summary>
    /// Overwrite all values except position.
    /// </summary>
    /// <param name="destination">
    /// the grid position of the node the pathfinder is trying to reach.
    /// </param>
    /// <param name="connection">
    /// the new connection to assign to the node.
    /// </param>
    /// <param name="cost">
    /// the new path cost to assign to the node.
    /// </param>
    public void Reset(IVec2 destination, PathConnection? connection, float cost) {
        PathCost = cost;
        Connection = connection;
        IVec2 distance = GridPos - destination;
        Heuristic = Mathf.Sqrt(
            distance.x * distance.x
            + distance.y * distance.y
        );
    }
}

/// <summary>
/// Connection between <see cref="PathNode">nodes</see> used by the pathfinding algorithm.
/// </summary>
public struct PathConnection {
    public ConnectionType Type;
    public PathNode Next;
    public PathConnection(ConnectionType type, PathNode next) {
        Type = type;
        Next = next;
    }
}

/// <summary>
/// Graph node representing all tiles the slugcat is able to actively perform movement on.
/// </summary>
public class Node {
    public NodeType Type;
    public bool VerticalBeam;
    public bool HorizontalBeam;
    public bool HasPlatform;
    public List<NodeConnection> Connections;
    public IVec2 GridPos;

    public Node(NodeType type, int x, int y) {
        Type = type;
        GridPos = new IVec2(x, y);
        Connections = new();
    }

    public bool HasBeam => VerticalBeam || HorizontalBeam;
}

/// <summary>
/// Tagged union representing different variants of <see cref="Node">graph nodes.</see>
/// </summary>
public record NodeType {
    public record Air() : NodeType();
    public record Floor() : NodeType();
    public record Slope() : NodeType();
    public record Corridor() : NodeType();
    public record ShortcutEntrance(int Index) : NodeType();
    public record Wall(int Direction) : NodeType();

    private NodeType() { }
}

/// <summary>
/// connection between <see cref="Node">graph nodes</see>.
/// </summary>
public class NodeConnection {
    public ConnectionType Type;
    public Node Next;
    public float Weight;

    public NodeConnection(ConnectionType type, Node next, float weight = 1f) {
        if (next is null) {
            throw new NoNullAllowedException();
        }
        Next = next;
        Weight = weight;
        Type = type;
    }
}

/// <summary>
/// List of node positions the slugcat should allow itself to pass through without taking action, providing easy iteration across ticks.
/// </summary>
public class IgnoreList {
    private int _cursor;
    private List<IVec2> _ignoreList;

    public IgnoreList() {
        _cursor = 0;
        _ignoreList = new();
    }

    public void Add(IVec2 node) {
        _ignoreList.Add(node);
    }

    /// <summary>
    /// Iterate through the list to check if it contains the requested tile position.
    /// entries checked during previous calls to this method are not checked again on repeated invocations.
    /// </summary>
    public bool ShouldIgnore(IVec2 node) {
        while (_cursor < _ignoreList.Count) {
            if (node == _ignoreList[_cursor]) {
                return true;
            }
            _cursor++;
        }
        return false;
    }

    /// <summary>
    /// Make a deep copy of the list.
    /// </summary>
    public IgnoreList Clone() {
        var cloneList = new List<IVec2>();
        cloneList.AddRange(_ignoreList);
        var clone = new IgnoreList() {
            _cursor = _cursor,
            _ignoreList = cloneList,
        };
        return clone;
    }
}

/// <summary>
/// Tagged union representing different variants of connections between <see cref="Node">graph nodes.</see>
/// </summary>
public record ConnectionType {
    public record Walk(int Direction) : ConnectionType();
    public record Climb(IVec2 Direction) : ConnectionType();
    public record Crawl(IVec2 Direction) : ConnectionType();
    public record Jump(int Direction) : ConnectionType();
    public record WalkOffEdge(int Direction) : ConnectionType();
    public record Pounce(int Direction) : ConnectionType();
    public record Shortcut() : ConnectionType();
    public record Drop(IgnoreList IgnoreList) : ConnectionType();

    private ConnectionType() { }
}

/// <summary>
/// Stores nodes and connections for a given room. The connections are not dependent on slugcat specific data,
/// slugcat-specific connections like jumps should be stored in <see cref="DynamicGraph">dynamic graphs</see> instead.
/// </summary>
public class SharedGraph {
    public Node?[,] Nodes;
    public int Width;
    public int Height;

    /// <summary>
    /// Create a new shared graph for a given rooms geometry.
    /// </summary>
    public SharedGraph(Room room) {
        Width = room.Tiles.GetLength(0);
        Height = room.Tiles.GetLength(1);
        Nodes = new Node[Width, Height];
        GenerateNodes(room);
        GenerateConnections(room);
    }

    /// <summary>
    /// Bounds checked access to the graph.
    /// </summary>
    /// <returns>
    /// Null if the requested coordinates are out of bounds or the graph does not contain a node at that position.
    /// </returns>
    public Node? GetNode(int x, int y) {
        if (Nodes is null || x < 0 || y < 0 || x >= Width || y >= Height) {
            return null;
        }
        return Nodes[x, y];
    }

    public Node? GetNode(IVec2 pos) {
        return GetNode(pos.x, pos.y);
    }

    /// <summary>
    /// Find the node the requested slugcat is currently at.
    /// </summary>
    /// <returns>
    /// Null if the slugcat is not located at any node in the graph.
    /// </returns>
    public Node? CurrentNode(Player player) {
        IVec2 pos = RoomHelper.TilePosition(player.bodyChunks[1].pos);
        if (player.bodyMode == Player.BodyModeIndex.Stand
            || player.animation == Player.AnimationIndex.StandOnBeam
        ) {
            return GetNode(pos) is Node node ? node : GetNode(pos.x, pos.y - 1);
        } else if (player.animation == Player.AnimationIndex.HangFromBeam) {
            return GetNode(pos.x, pos.y + 1);
        } else if (player.bodyMode == Player.BodyModeIndex.Crawl
            || player.bodyMode == Player.BodyModeIndex.CorridorClimb
        ) {
            IVec2 headPos = RoomHelper.TilePosition(player.bodyChunks[0].pos);
            return GetNode(headPos);
        }
        return GetNode(pos);
    }

    /// <summary>
    /// Generate the nodes making up the graph.
    /// </summary>
    private void GenerateNodes(Room room) {
        for (int y = 0; y < Height; y++) {
            for (int x = 0; x < Width; x++) {
                if (x - 1 < 0 || x + 1 >= Width || y - 1 < 0 || y + 1 >= Height) {
                    continue;
                }
                if (room.Tiles[x, y].Terrain == Room.Tile.TerrainType.Solid) {
                    continue;
                } else if (room.Tiles[x, y].Terrain == Room.Tile.TerrainType.Floor) {
                    if (room.Tiles[x - 1, y].Terrain == Room.Tile.TerrainType.Solid && room.Tiles[x + 1, y].Terrain == Room.Tile.TerrainType.Solid) {
                        Nodes[x, y] = new Node(new NodeType.Corridor(), x, y) {
                            HasPlatform = true,
                        };
                    }
                } else if (room.Tiles[x, y].Terrain == Room.Tile.TerrainType.Air) {
                    if (!(room.Tiles[x - 1, y].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x - 1, y + 1].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x, y + 1].Terrain == Room.Tile.TerrainType.Air)
                        && !(room.Tiles[x + 1, y].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x + 1, y + 1].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x, y + 1].Terrain == Room.Tile.TerrainType.Air)
                        && !(room.Tiles[x - 1, y].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x - 1, y - 1].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x, y - 1].Terrain == Room.Tile.TerrainType.Air)
                        && !(room.Tiles[x + 1, y].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x + 1, y - 1].Terrain == Room.Tile.TerrainType.Air
                            && room.Tiles[x, y - 1].Terrain == Room.Tile.TerrainType.Air)
                    ) {
                        Nodes[x, y] = new Node(new NodeType.Corridor(), x, y);
                    } else if (
                          room.Tiles[x, y - 1].Terrain == Room.Tile.TerrainType.Solid
                          || room.Tiles[x, y - 1].Terrain == Room.Tile.TerrainType.ShortcutEntrance
                          // pretend invalid slope is solid
                          || room.Tiles[x, y - 1].Terrain == Room.Tile.TerrainType.Slope
                          && room.Tiles[x - 1, y - 1].Terrain == Room.Tile.TerrainType.Solid
                          && room.Tiles[x + 1, y - 1].Terrain == Room.Tile.TerrainType.Solid
                    ) {
                        Nodes[x, y] = new Node(new NodeType.Floor(), x, y);
                    } else if (room.Tiles[x, y - 1].Terrain == Room.Tile.TerrainType.Floor) {
                        Nodes[x, y] = new Node(new NodeType.Floor(), x, y);
                    } else if (room.Tiles[x - 1, y].Terrain == Room.Tile.TerrainType.Air
                          && room.Tiles[x + 1, y].Terrain == Room.Tile.TerrainType.Solid) {
                        Nodes[x, y] = new Node(new NodeType.Wall(1), x, y);
                    } else if (room.Tiles[x - 1, y].Terrain == Room.Tile.TerrainType.Solid
                          && room.Tiles[x + 1, y].Terrain == Room.Tile.TerrainType.Air) {
                        Nodes[x, y] = new Node(new NodeType.Wall(-1), x, y);
                    }
                } else if (room.Tiles[x, y].Terrain == Room.Tile.TerrainType.Slope
                      && room.Tiles[x, y + 1].Terrain == Room.Tile.TerrainType.Air
                      && !(room.Tiles[x - 1, y].Terrain == Room.Tile.TerrainType.Solid
                          && room.Tiles[x + 1, y].Terrain == Room.Tile.TerrainType.Solid)) {
                    Nodes[x, y] = new Node(new NodeType.Slope(), x, y);
                } else if (room.Tiles[x, y].Terrain == Room.Tile.TerrainType.ShortcutEntrance) {
                    int index = Array.IndexOf(room.shortcutsIndex, new IVec2(x, y));
                    if (index > -1 && room.shortcuts[index].shortCutType == ShortcutData.Type.Normal) {
                        Nodes[x, y] = new Node(new NodeType.ShortcutEntrance(index), x, y);
                    }
                }

                if (room.Tiles[x, y].verticalBeam) {
                    if (Nodes[x, y] is null) {
                        Nodes[x, y] = new Node(new NodeType.Air(), x, y);
                    }
                    Nodes[x, y]!.VerticalBeam = true;
                }

                if (room.Tiles[x, y].horizontalBeam) {
                    if (Nodes[x, y] is null) {
                        Nodes[x, y] = new Node(new NodeType.Air(), x, y);
                    }
                    Nodes[x, y]!.HorizontalBeam = true;
                }
            }
        }
    }

    /// <summary>
    /// Generate connections between nodes in the graph.
    /// </summary>
    private void GenerateConnections(Room room) {
        for (int y = 0; y < Height; y++) {
            for (int x = 0; x < Width; x++) {
                if (Nodes[x, y] is null) {
                    continue;
                }
                if (Nodes[x, y]!.Type is NodeType.Floor) {
                    if (GetNode(x + 1, y)?.Type is NodeType.Floor or NodeType.Slope) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y]!,
                            new ConnectionType.Walk(1),
                            new ConnectionType.Walk(-1)
                        );
                    } else if (GetNode(x + 1, y)?.Type is NodeType.Corridor) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y]!,
                            new ConnectionType.Crawl(new IVec2(1, 0)),
                            new ConnectionType.Crawl(new IVec2(-1, 0))
                        );
                    }
                    if (GetNode(x + 1, y - 1)?.Type is NodeType.Slope) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y - 1]!,
                            new ConnectionType.Walk(1),
                            new ConnectionType.Walk(-1)
                        );
                    }
                    if (GetNode(x + 1, y + 1)?.Type is NodeType.Corridor) {
                        Nodes[x, y]!.Connections.Add(new NodeConnection(new ConnectionType.Walk(1), Nodes[x + 1, y + 1]!));
                    }
                }

                if (Nodes[x, y]!.Type is NodeType.Slope) {
                    if (GetNode(x + 1, y)?.Type is NodeType.Floor or NodeType.Slope) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y]!,
                            new ConnectionType.Walk(1),
                            new ConnectionType.Walk(-1)
                        );
                    } else if (GetNode(x + 1, y - 1)?.Type is NodeType.Slope) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y - 1]!,
                            new ConnectionType.Walk(1),
                            new ConnectionType.Walk(-1)
                        );
                    } else if (GetNode(x + 1, y + 1)?.Type is NodeType.Slope or NodeType.Floor) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y + 1]!,
                            new ConnectionType.Walk(1),
                            new ConnectionType.Walk(-1)
                        );
                    }
                }

                var rightNode = GetNode(x + 1, y);
                var aboveNode = GetNode(x, y + 1);
                if (Nodes[x, y]!.Type is NodeType.Corridor) {
                    if (rightNode?.Type is NodeType.Corridor or NodeType.Floor or NodeType.ShortcutEntrance) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            rightNode,
                            new ConnectionType.Crawl(new IVec2(1, 0)),
                            new ConnectionType.Crawl(new IVec2(-1, 0))
                        );
                    } else if (rightNode?.HorizontalBeam == true) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            rightNode,
                            new ConnectionType.Crawl(new IVec2(1, 0)),
                            rightNode.HorizontalBeam
                                ? new ConnectionType.Climb(new IVec2(-1, 0))
                                : new ConnectionType.Crawl(new IVec2(-1, 0))
                        );
                    }
                    if (GetNode(x + 1, y - 1)?.Type is NodeType.Floor) {
                        Nodes[x + 1, y - 1]!.Connections.Add(new NodeConnection(new ConnectionType.Walk(-1), Nodes[x, y]!));
                    }
                    if (aboveNode?.Type is NodeType.Corridor or NodeType.ShortcutEntrance or NodeType.Floor) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            aboveNode,
                            new ConnectionType.Crawl(new IVec2(0, 1)),
                            new ConnectionType.Crawl(new IVec2(0, -1))
                        );
                    } else if (aboveNode?.Type is NodeType.Floor) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            aboveNode,
                            new ConnectionType.Crawl(new IVec2 (0, 1)),
                            new ConnectionType.Crawl(new IVec2 (0, -1))
                        );
                    }
                } else {
                    if (Nodes[x, y]!.HorizontalBeam
                        && rightNode?.HorizontalBeam == true
                    ) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y]!,
                            new ConnectionType.Climb(new IVec2(1, 0)),
                            rightNode.Type is NodeType.Corridor
                                ? new ConnectionType.Crawl(new IVec2(-1, 0))
                                : new ConnectionType.Climb(new IVec2(-1, 0))
                        );
                    }
                    if (Nodes[x, y]!.VerticalBeam
                        && aboveNode?.VerticalBeam == true
                    ) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            aboveNode,
                            new ConnectionType.Climb(new IVec2(0, 1)),
                            aboveNode.Type is NodeType.Corridor
                                ? new ConnectionType.Crawl(new IVec2(0, -1))
                                : new ConnectionType.Climb(new IVec2(0, -1))
                        );

                    }
                }
                if (Nodes[x, y]!.Type is NodeType.ShortcutEntrance) {
                    var entrance = Nodes[x, y]!.Type as NodeType.ShortcutEntrance;
                    var shortcutData = room.shortcuts[entrance!.Index];
                    var destNode = Nodes[shortcutData.destinationCoord.x, shortcutData.destinationCoord.y];
                    if (destNode is null || destNode.Type is not NodeType.ShortcutEntrance) {
                        Plugin.Logger!.LogError($"Shortcut entrance has no valid exit, pos: ({x}, {y}), index: {entrance.Index}");
                        return;
                    }
                    Nodes[x, y]!.Connections.Add(new NodeConnection(new ConnectionType.Shortcut(), destNode, shortcutData.length));
                    if (GetNode(x + 1, y)?.Type is NodeType.Corridor) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x + 1, y]!,
                            new ConnectionType.Crawl(new IVec2(1, 0)),
                            new ConnectionType.Crawl(new IVec2(-1, 0))
                        );
                    }
                    if (GetNode(x, y + 1)?.Type is NodeType.Corridor) {
                        ConnectNodes(
                            Nodes[x, y]!,
                            Nodes[x, y + 1]!,
                            new ConnectionType.Crawl(new IVec2(0, 1)),
                            new ConnectionType.Crawl(new IVec2(0, -1))
                        );
                    }
                }
            }
        }
    }

    /// <summary>
    /// Make a bidirectional connection between two nodes in the graph.
    /// </summary>
    private void ConnectNodes(Node start, Node end, ConnectionType startToEndType, ConnectionType endToStartType, float weight = 1f) {
        start.Connections.Add(new NodeConnection(startToEndType, end, weight));
        end.Connections.Add(new NodeConnection(endToStartType, start, weight));
    }
}

/// <summary>
/// Stores connections dependent on slugcat-specific values like jumps.
/// </summary>
public class DynamicGraph {
    private Room _room;

    public List<NodeConnection>[,] AdjacencyLists;
    public int Width;
    public int Height;

    /// <summary>
    /// Create empty adjacencly lists at positions with a corresponding <see cref="Node">graph node</see>.
    /// </summary>
    public DynamicGraph(Room room) {
        _room = room;
        var sharedGraph = room.GetCWT().SharedGraph!;
        Width = sharedGraph.Width;
        Height = sharedGraph.Height;
        AdjacencyLists = new List<NodeConnection>[Width, Height];
        for (int y = 0; y < Height; y++) {
            for (int x = 0; x < Width; x++) {
                if (sharedGraph.Nodes[x, y] is not null) {
                    AdjacencyLists[x, y] = new();
                }
            }
        }
    }

    /// <summary>
    /// Reinitialize the graph for the new room. Does nothing if the room hasn't actually changed.
    /// </summary>
    public void NewRoom(Room room) {
        if (room != _room) {
            _room = room;
            var sharedGraph = room.GetCWT().SharedGraph!;
            Width = sharedGraph.Width;
            Height = sharedGraph.Height;
            AdjacencyLists = new List<NodeConnection>[Width, Height];
            for (int y = 0; y < Height; y++) {
                for (int x = 0; x < Width; x++) {
                    if (sharedGraph.Nodes[x, y] is not null) {
                        AdjacencyLists[x, y] = new();
                    }
                }
            }
        }
    }

    /// <summary>
    /// Calculate dynamic connections starting at the specified tile position.
    /// </summary>
    /// <param name="pos">
    /// the tile position to trace from.
    /// </param>
    /// <param name="descriptor">
    /// slugcat-specifc values to use.
    /// </param>
    public void TraceFromNode(IVec2 pos, SlugcatDescriptor descriptor) {
        if (Timers.Active) {
            Timers.TraceFromNode.Start();
        }
        var sharedGraph = _room.GetCWT().SharedGraph!;
        var graphNode = sharedGraph.GetNode(pos);
        if (graphNode is null) {
            if (Timers.Active) {
                Timers.TraceFromNode.Stop();
            }
            return;
        }
        bool goLeft = true;
        bool goRight = true;
        if (graphNode.Type is NodeType.Wall(int direction)) {
            if (direction == -1) {
                goLeft = false;
            } else {
                goRight = false;
            }
        }
        if (sharedGraph.GetNode(pos.x, pos.y - 1)?.Type is NodeType.Wall footWall) {
            if (footWall.Direction == -1) {
                goLeft = false;
            } else {
                goRight = false;
            }
        }
        if (graphNode.VerticalBeam && !graphNode.HorizontalBeam
            && graphNode.Type is not (NodeType.Corridor or NodeType.Floor or NodeType.Slope)
            && sharedGraph.GetNode(pos.x, pos.y - 1)?.Type is not (NodeType.Corridor or NodeType.Floor or NodeType.Slope)) {
            Vector2 v0 = descriptor.VerticalPoleJumpVector();
            if (goRight) {
                TraceJump(pos, pos, v0, new ConnectionType.Jump(1));
            }
            if (goLeft) {
                v0.x = -v0.x;
                TraceJump(pos, pos, v0, new ConnectionType.Jump(-1));
            }
            TraceDrop(pos.x, pos.y);
        }
        if (graphNode.HorizontalBeam && graphNode.Type is not (NodeType.Corridor or NodeType.Floor or NodeType.Slope)) {
            var headPos = new IVec2(pos.x, pos.y + 1);
            var v0 = descriptor.HorizontalPoleJumpVector();
            if (goRight) {
                TraceJump(pos, headPos, v0, new ConnectionType.Jump(1));
            }
            if (goLeft) {
                v0.x = -v0.x;
                TraceJump(pos, headPos, v0, new ConnectionType.Jump(-1));
            }
            TraceDrop(pos.x, pos.y);
        }
        if (graphNode.Type is NodeType.Floor) {
            var headPos = new IVec2(pos.x, pos.y + 1);
            var v0 = descriptor.FloorJumpVector();
            if (goRight) {
                TraceJump(pos, headPos, v0, new ConnectionType.Jump(1));
                if (sharedGraph.GetNode(pos.x + 1, pos.y - 1)?.Type is NodeType.Wall) {
                    v0.y = 0f;
                    TraceJump(pos, headPos, v0, new ConnectionType.WalkOffEdge(1));
                }
            }
            if (goLeft) {
                v0.x = -v0.x;
                TraceJump(pos, headPos, v0, new ConnectionType.Jump(-1));
                if (sharedGraph.GetNode(pos.x - 1, pos.y - 1)?.Type is NodeType.Wall) {
                    v0.y = 0f;
                    TraceJump(pos, headPos, v0, new ConnectionType.WalkOffEdge(-1));
                }
            }

        } else if (graphNode.Type is NodeType.Corridor) {
            var v0 = descriptor.HorizontalCorridorFallVector();
            // v0.x might be too large
            if (sharedGraph.GetNode(pos.x + 1, pos.y) is null) {
                TraceJump(pos, pos, v0, new ConnectionType.WalkOffEdge(1), upright: false);
            }
            if (sharedGraph.GetNode(pos.x - 1, pos.y) is null) {
                v0.x = -v0.x;
                TraceJump(pos, pos, v0, new ConnectionType.WalkOffEdge(-1), upright: false);
            }
            if (sharedGraph.GetNode(pos.x, pos.y - 1) is null
                && _room.Tiles[pos.x, pos.y - 1].Terrain == Room.Tile.TerrainType.Air
            ) {
                TraceDrop(pos.x, pos.y);
            }
        } else if (graphNode.Type is NodeType.Wall jumpWall) {
            var v0 = descriptor.WallJumpVector(jumpWall.Direction);
            TraceJump(pos, pos, v0, new ConnectionType.Jump(-jumpWall.Direction));
        }
        if (Timers.Active) {
            Timers.TraceFromNode.Stop();
        }
    }

    /// <summary>
    /// Calculate the altitude along the traced trajectory at a specified point in time.
    /// </summary>
    /// <param name="yOffset">
    /// the starting position of the trajectory.
    /// </param>
    /// <param name="v0">
    /// the velocity vector at t = 0.
    /// </param>
    /// <param name="g">
    /// the acceleration due to gravity.
    /// </param>
    public static float Parabola(float yOffset, Vector2 v0, float g, float t) => v0.y * t - 0.5f * g * t * t + yOffset;

    /// <summary>
    /// Trace parabolic trajectory through the shared graph and add any found connections to the dynamic graph.
    /// </summary>
    /// <param name="startPos">
    /// the tile position of the node generated connections should start from.
    /// </param>
    /// <param name="headPos">
    /// the tile position of the first bodychunk at the start of the jump, corresponding roughly to the head position.
    /// </param>
    /// <param name="v0">
    /// the velocity vector at the start of the jump.
    /// </param>
    /// <param name="type">
    /// the type assigned to traced connections.
    /// </param>
    /// <param name="upright">
    /// whether the slugcat should be treated as falling upright or head first during.
    /// </param>
    private void TraceJump(
        IVec2 startPos,
        IVec2 headPos,
        Vector2 v0,
        ConnectionType type,
        bool upright = true
    ) {
        int x = headPos.x;
        int y = headPos.y;
        var sharedGraph = _room.GetCWT().SharedGraph;
        if (x < 0 || y < 0 || x >= Width || y >= Height || sharedGraph is null) {
            return;
        }
        int direction = v0.x switch {
            > 0 => 1,
            < 0 => -1,
            0 or float.NaN => throw new ArgumentOutOfRangeException(),
        };
        int xOffset = (direction + 1) / 2;
        var pathOffset = RoomHelper.MiddleOfTile(headPos);

        var startConnectionList = AdjacencyLists[startPos.x, startPos.y];
        while (true) {
            float t = (20 * (x + xOffset) - pathOffset.x) / v0.x;
            float result = Parabola(pathOffset.y, v0, _room.gravity, t) / 20;
            if (result > y + 1) {
                y++;
            } else if (result < y) {
                if (y - 2 < 0) {
                    break;
                }
                var currentNode = sharedGraph.Nodes[x, upright ? y - 1 : y];
                if (currentNode?.Type is NodeType.Floor or NodeType.Slope) {
                    startConnectionList.Add(new NodeConnection(type, currentNode, t * 20 / 4.2f + 1));
                }
                if (_room.Tiles[x, upright ? y - 2 : y - 1].Terrain == Room.Tile.TerrainType.Solid) {
                    break;
                }
                y--;
            } else {
                x += direction;
            }

            if (x < 0 || y < 0 || x >= Width || y >= Height
                || _room.Tiles[x, y].Terrain == Room.Tile.TerrainType.Solid
                || _room.Tiles[x, y].Terrain == Room.Tile.TerrainType.Slope) {
                break;
            }

            var shiftedNode = sharedGraph.Nodes[x, y];
            if (shiftedNode is null) {
                continue;
            }
            if (shiftedNode.Type is NodeType.Corridor) {
                break;
            }
            if (shiftedNode.Type is NodeType.Wall wall && wall.Direction == direction) {
                startConnectionList.Add(new NodeConnection(type, shiftedNode, t * 4.2f / 20));
                break;
            } else if (shiftedNode.VerticalBeam) {
                float poleResult = Parabola(pathOffset.y, v0, _room.gravity, (20 * x + 10 - pathOffset.x) / v0.x) / 20;
                if (poleResult > y && poleResult < y + 1) {
                    startConnectionList.Add(new NodeConnection(type, shiftedNode, t * 4.2f / 20 + 5));
                }
            } else if (shiftedNode.HorizontalBeam) {
                startConnectionList.Add(new NodeConnection(type, shiftedNode, t * 4.2f / 20 + 10));
            }
        }
    }

    /// <summary>
    /// Trace vertical drop from the specified tile coordinates.
    /// </summary>
    private void TraceDrop(int x, int y) {
        var sharedGraph = _room.GetCWT().SharedGraph!;
        if (sharedGraph.GetNode(x, y)?.Type is NodeType.Floor or NodeType.Slope
            || y >= sharedGraph.Height
        ) {
            return;
        }
        var adjacencyList = AdjacencyLists[x, y]!;
        var ignoreList = new IgnoreList();
        for (int i = y - 1; i >= 0; i--) {
            if (sharedGraph.Nodes[x, i] is null) {
                continue;
            }
            var currentNode = sharedGraph.Nodes[x, i]!;
            if (sharedGraph.Nodes[x, i]!.Type is NodeType.Floor) {
                // t = sqrt(2 * d / g)
                // weight might have inaccurate units
                adjacencyList.Add(
                    new NodeConnection(
                        new ConnectionType.Drop(ignoreList),
                        currentNode,
                        Mathf.Sqrt(2 * 20 * (y - i) / _room.gravity) * 4.2f / 20
                    )
                );
                if (sharedGraph.GetNode(x, i - 1)?.HasPlatform is false or null) {
                    break;
                }
            } else if (currentNode.Type is not NodeType.Air or NodeType.Wall) {
                adjacencyList.Add(
                    new NodeConnection(
                        new ConnectionType.Drop(ignoreList.Clone()),
                        currentNode,
                        Mathf.Sqrt(2 * 20 * (y - i) / _room.gravity) * 4.2f / 20
                    )
                );
                break;
            } else if (currentNode.HorizontalBeam) {
                adjacencyList.Add(
                    new NodeConnection(
                        new ConnectionType.Drop(ignoreList.Clone()),
                        currentNode,
                        Mathf.Sqrt(2 * 20 * (y - i) / _room.gravity)
                    )
                );
                ignoreList.Add(new IVec2(x, i));
            } else {
                break;
            }
        }
    }
}

/// <summary>
/// slugcat-specific values that may or may not be able to change over time.
/// </summary>
public readonly struct SlugcatDescriptor {
    public readonly bool IsRivulet;
    public readonly bool IsPup;
    public readonly float Adrenaline;
    public readonly float Runspeed;
    public SlugcatDescriptor(Player player) {
        IsRivulet = player.isRivulet;
        IsPup = player.isSlugpup;
        Adrenaline = player.Adrenaline;
        Runspeed = player.slugcatStats.runspeedFac;
    }

    public override readonly bool Equals(object obj) {
        return base.Equals(obj);
    }

    public override readonly int GetHashCode() {
        return base.GetHashCode();
    }

    public static bool operator ==(SlugcatDescriptor self, SlugcatDescriptor other) {
        return self.IsRivulet == other.IsRivulet
            && self.IsPup == other.IsPup
            && self.Adrenaline == other.Adrenaline
            && self.Runspeed == other.Runspeed;
    }

    public static bool operator !=(SlugcatDescriptor self, SlugcatDescriptor other) {
        return self.IsRivulet != other.IsRivulet
            || self.IsPup != other.IsPup
            || self.Adrenaline != other.Adrenaline
            || self.Runspeed != other.Runspeed;
    }

    public static float JumpBoost(float boost) {
        float t = Mathf.Ceil(boost / 1.5f);
        return 0.3f * ((boost - 0.5f) * t - 0.75f * t * t);
    }

    public readonly Vector2 FloorJumpVector() {
        return new Vector2(
            4.2f * Runspeed * Mathf.Lerp(1, 1.5f, Adrenaline),
            (IsRivulet ? 6f : 4f) * Mathf.Lerp(1, 1.15f, Adrenaline) + JumpBoost(IsPup ? 7 : 8));
    }

    public readonly Vector2 HorizontalPoleJumpVector() {
        Vector2 v0;
        if (IsRivulet) {
            v0 = new Vector2(9f, 9f) * Mathf.Lerp(1, 1.15f, Adrenaline);
        } else if (IsPup) {
            v0 = new Vector2(5f, 7f) * Mathf.Lerp(1, 1.15f, Adrenaline);
        } else {
            v0 = new Vector2(6f, 8f) * Mathf.Lerp(1, 1.15f, Adrenaline);
        }
        return v0;
    }

    public readonly Vector2 VerticalPoleJumpVector() {
        return new Vector2(
            4.2f * Runspeed * Mathf.Lerp(1, 1.5f, Adrenaline),
            (IsRivulet ? 6f : 4f) * Mathf.Lerp(1, 1.15f, Adrenaline) + JumpBoost(IsPup ? 7 : 8)
        );
    }

    public readonly Vector2 HorizontalCorridorFallVector() {
        return new Vector2(
            4.2f * Runspeed * Mathf.Lerp(1, 1.5f, Adrenaline),
            0);
    }

    public readonly Vector2 WallJumpVector(int wallDirection) {
        Vector2 v0;
        if (IsRivulet) {
            v0 = new Vector2(-wallDirection * 9, 10) * Mathf.Lerp(1, 1.15f, Adrenaline);
        } else if (IsPup) {
            v0 = new Vector2(-wallDirection * 5, 6) * Mathf.Lerp(1, 1.15f, Adrenaline);
        } else {
            v0 = new Vector2(-wallDirection * 6, 8) * Mathf.Lerp(1, 1.15f, Adrenaline);
        }
        return v0;
    }
}

/// <summary>
/// A two dimensional packed array of bits.
/// </summary>
public class BitGrid {
    private readonly BitArray _array;

    public int Width { get; }
    public int Height { get; }

    public BitGrid(int width, int height) {
        Width = width;
        Height = height;
        _array = new BitArray(width * height);
    }

    public bool this[int x, int y] {
        get => _array[y * Width + x];
        set {
            _array[y * Width + x] = value;
        }
    }

    public bool this[IVec2 pos] {
        get => _array[pos.y * Width + pos.x];
        set {
            _array[pos.y * Width + pos.x] = value;
        }
    }

    /// <summary>
    /// set every bit to zero.
    /// </summary>
    public void Reset() {
        _array.SetAll(false);
    }
}

public class PathNodeQueue {
    private readonly List<PathNode> _nodes;
    private readonly int[,] _indexMap;

    public int Count => _nodes.Count;
    public int Width => _indexMap.GetLength(0);
    public int Height => _indexMap.GetLength(1);
    public PathNode? Root => _nodes.Count > 0 ? _nodes[0] : null;

    public PathNodeQueue(int capacity, int width, int height) {
        _nodes = new(capacity);
        _indexMap = new int[width, height];
        ResetMap();
    }

    public void Reset() {
        _nodes.Clear();
        ResetMap();
    }

    private void ResetMap() {
        for (int y = 0; y < Height; y++) {
            for (int x = 0; x < Width; x++) {
                _indexMap[x, y] = -1;
            }
        }
    }

    public void Add(PathNode node) {
        _nodes.Add(node);
        IVec2 pos = node.GridPos;
        _indexMap[pos.x, pos.y] = _nodes.Count - 1;
        MoveUp(_nodes.Count - 1);
    }

    public void DecreasePriority(IVec2 pos) {
        int index = _indexMap[pos.x, pos.y];
        if (index < 0) {
            throw new ArgumentOutOfRangeException();
        }
        MoveUp(index);
    }

    private void MoveUp(int index) {
        while (index > 0 && _nodes[index].FCost < _nodes[(index - 1) / 2].FCost) {
            Swap(index, (index - 1) / 2);
            index = (index - 1) / 2;
        }
    }

    private void Swap(int i, int j) {
        (_nodes[i], _nodes[j]) = (_nodes[j], _nodes[i]);
        IVec2 a = _nodes[i].GridPos;
        IVec2 b = _nodes[j].GridPos;
        (_indexMap[b.x, b.y], _indexMap[a.x, a.y]) = (_indexMap[a.x, a.y], _indexMap[b.x, b.y]);
    }

    public void RemoveRoot() {
        _nodes[0] = _nodes[_nodes.Count - 1];
        IVec2 pos = _nodes[0].GridPos;
        _indexMap[pos.x, pos.y] = 0;
        _nodes.Pop();
        int index = 0;
        int leftIndex = 1;
        int rightIndex = 2;
        while (true) {
            if (rightIndex < _nodes.Count) {
                float parentCost = _nodes[index].FCost;
                float leftCost = _nodes[leftIndex].FCost;
                float rightCost = _nodes[rightIndex].FCost;
                if (leftCost < parentCost) {
                    if (rightCost < parentCost) {
                        if (leftCost < rightCost) {
                            Swap(index, leftIndex);
                            index = leftIndex;
                        } else {
                            Swap(index, rightIndex);
                            index = rightIndex;
                        }
                    } else {
                        Swap(index, leftIndex);
                        index = leftIndex;
                    }
                } else if (rightCost < parentCost) {
                    Swap(index, rightIndex);
                    index = rightIndex;
                } else {
                    // heap in order
                    break;
                }
            } else if (leftIndex < _nodes.Count) {
                float parentCost = _nodes[index].FCost;
                float leftCost = _nodes[leftIndex].FCost;
                if (leftCost < parentCost) {
                    Swap(index, leftIndex);
                    index = leftIndex;
                } else {
                    // heap in order
                    break;
                }
            } else {
                // no children
                break;
            }
            leftIndex = 2 * index + 1;
            rightIndex = 2 * index + 2;
        }
    }

    public bool Validate() {
        PathNode node;
        for (int i = 0; i < Count; i++) {
            node = _nodes[i];
            if (node.FCost < Root!.FCost) {
                return false;
            }
        }
        return true;
    }

    public string DebugList() {
        var validationString = new StringBuilder();
        for (int j = 0; j < Count; j++) {
            validationString.Append(_nodes[j].FCost);
            validationString.Append(" ");
        }
        return validationString.ToString();
    }
}

/// <summary>
/// An object pool allowing <see cref="PathNode">path nodes</see> to be reused between ticks and shared between pathfinders without deallocation.
/// </summary>
public readonly struct PathNodePool {
    private readonly PathNode?[,] _array;
    public readonly int NonNullCount;
    public readonly int Width => _array.GetLength(0);
    public readonly int Height => _array.GetLength(1);

    public PathNodePool(SharedGraph graph) {
        _array = new PathNode[graph.Width, graph.Height];
        for (int y = 0; y < Height; y++) {
            for (int x = 0; x < Width; x++) {
                if (graph.Nodes[x, y] is not null) {
                    _array[x, y] = new PathNode(x, y);
                    NonNullCount++;
                }
            }
        }
    }

    public readonly PathNode? this[int x, int y] => _array[x, y];
    public readonly PathNode? this[IVec2 pos] => _array[pos.x, pos.y];
}

public class Pathfinder {
    private Room _room;
    private SlugcatDescriptor _lastDescriptor;
    private readonly DynamicGraph _dynamicGraph;

    /// <summary>
    /// Create new pathfinder in the specified room.
    /// </summary>
    /// <param name="room">
    /// the room the pathfinder will try to find paths through
    /// </param>
    /// <param name="descriptor">
    /// relevant information about the slugcat using this pathfinder.
    /// </param>
    public Pathfinder(Room room, SlugcatDescriptor descriptor) {
        _room = room;
        _lastDescriptor = descriptor;
        _dynamicGraph = new DynamicGraph(room);
    }

    /// <summary>
    /// Reinitialize pathfinder for new room. Does nothing if the room has not actually changed.
    /// </summary>
    public void NewRoom(Room room) {
        if (room != _room) {
            _room = room;
            _dynamicGraph.NewRoom(room);
        }
    }

    /// <summary>
    /// Find fastest path between two coordinates.
    /// </summary>
    /// <param name="start">
    /// the start of the requested path.
    /// </param>
    /// <param name="destination">
    /// the end of the requested path.
    /// </param>
    /// <param name="descriptor">
    /// updated slugcat-specific values.
    /// </param>
    /// <returns>
    /// Null if no path could be found or the coordinates are invalid,
    /// otherwise returns a <see cref="Path">path</see> ready for use by the AI.
    /// </returns>
    public Path? FindPath(IVec2 start, IVec2 destination, SlugcatDescriptor descriptor) {
        var sharedGraph = _room.GetCWT().SharedGraph!;
        if (sharedGraph.GetNode(start) is null) {
            Plugin.Logger!.LogDebug($"no node at start ({start.x}, {start.y})");
            _lastDescriptor = descriptor;
            return null;
        }
        if (sharedGraph.GetNode(destination) is null) {
            Plugin.Logger!.LogDebug($"no node at destination ({destination.x}, {destination.y})");
            _lastDescriptor = descriptor;
            return null;
        }
        if (Timers.Active) {
            Timers.FindPath.Start();
        }
        var pathNodePool = _room.GetCWT().PathNodePool!.Value;
        var openNodes = _room.GetCWT().OpenNodes!;
        openNodes.Reset();
        var closedNodes = _room.GetCWT().ClosedNodes!;
        closedNodes.Reset();
        var startNode = pathNodePool[start]!;
        startNode.Reset(destination, null, 0);
        var nodeQueue = _room.GetCWT().NodeQueue!;
        nodeQueue.Reset();
        nodeQueue.Add(startNode);
        openNodes[start] = true;
        while (nodeQueue.Count > 0) {
            PathNode currentNode = nodeQueue.Root!;
            var currentPos = currentNode.GridPos;
            if (currentPos == destination) {
                if (Timers.Active) {
                    Timers.FindPath.Stop();
                }
                _lastDescriptor = descriptor;
                return new Path(currentNode);
            }
            nodeQueue.RemoveRoot();
            openNodes[currentPos] = false;
            closedNodes[currentPos] = true;

            var graphNode = sharedGraph.Nodes[currentPos.x, currentPos.y]!;
            var adjacencyList = _dynamicGraph.AdjacencyLists[currentPos.x, currentPos.y]!;

            if (adjacencyList.Count == 0) {
                _dynamicGraph.TraceFromNode(currentPos, descriptor);
            } else if (_lastDescriptor != descriptor) {
                adjacencyList.Clear();
                _dynamicGraph.TraceFromNode(currentPos, descriptor);
            }

            void CheckConnection(NodeConnection connection) {
                IVec2 neighbourPos = connection.Next.GridPos;
                PathNode currentNeighbour = pathNodePool[neighbourPos]!;
                if (closedNodes[neighbourPos]) {
                    return;
                }
                if (!openNodes[neighbourPos]) {
                    openNodes[neighbourPos] = true;
                    currentNeighbour.Reset(
                        destination,
                        new PathConnection(connection.Type, currentNode),
                        currentNode.PathCost + connection.Weight
                    );
                    nodeQueue.Add(currentNeighbour);
                }
                if (currentNode.PathCost + connection.Weight < currentNeighbour.PathCost) {
                    currentNeighbour.PathCost = currentNode.PathCost + connection.Weight;
                    currentNeighbour.Connection = new PathConnection(connection.Type, currentNode);
                    nodeQueue.DecreasePriority(currentNeighbour.GridPos);
                }
            }

            foreach (var connection in graphNode.Connections) {
                CheckConnection(connection);
            }
            foreach (var connection in adjacencyList) {
                CheckConnection(connection);
            }
        }
        if (Timers.Active) {
            Timers.FindPath.Stop();
        }
        _lastDescriptor = descriptor;
        return null;
    }
}

static class PathfinderHooks {
    public static void RegisterHooks() {
        On.Player.ctor += Player_ctor;
        On.Player.Update += Player_Update;
    }

    public static void UnregisterHooks() {
        On.Player.ctor -= Player_ctor;
        On.Player.Update -= Player_Update;
    }

    private static void Player_ctor(On.Player.orig_ctor orig, Player self, AbstractCreature abstractCreature, World world) {
        orig(self, abstractCreature, world);
    }

    private static void Player_Update(On.Player.orig_Update orig, Player self, bool eu) {
        if (self.abstractCreature?.abstractAI is null) {
            var mousePos = (Vector2)Input.mousePosition + self.room.game.cameras[0].pos;
            if (InputHelper.JustPressedMouseButton(1)) {
                var scugTemplate = StaticWorld.GetCreatureTemplate(MoreSlugcatsEnums.CreatureTemplateType.SlugNPC);
                var abstractScug = new AbstractCreature(
                    self.room.world,
                    scugTemplate,
                    null,
                    self.room.ToWorldCoordinate(mousePos),
                    self.room.game.GetNewID());
                abstractScug.state = new PlayerNPCState(abstractScug, 0) {
                    forceFullGrown = true,
                };
                self.room.abstractRoom.AddEntity(abstractScug);
                abstractScug.RealizeInRoom();
                abstractScug.abstractAI = new JumpSlugAbstractAI(abstractScug, self.room.world) {
                    RealAI = new JumpSlugAI(abstractScug, self.room.world),
                };
                var realizedScug = (abstractScug.realizedCreature as Player)!;
                realizedScug.controller = null;
            }
        }
        orig(self, eu);
    }
}